
dubbo:
  application:
    name: dubbo-web

  registry:
    address: zookeeper://47.115.207.7:2181
    username: root
    password: ilovetimhooper
  scan:
    base-packages: com.hooper.dubbo.controller


server:
  port: 9002

logging:
  level:
    dubbo:
        com.hooper.dubbo.controller: trace