
dubbo:
  application:
    name: dubbo-service
  protocol:
    port: 20800
  registry:
    address: zookeeper://47.115.207.7:2181
    username: root
    password: ilovetimhooper
  scan:
    base-packages: com.hooper.dubbo.service
  provider:
    # 负载均衡策略： 轮询
    loadbalance: roundrobin
server:
  port: 8000

logging:
  level:
    dubbo:
      com.hooper.dubbo.controller: trace